function createhgtransform(Parent1, XMatrix1, YMatrix1, ZMatrix1)
%CREATEHGTRANSFORM(PARENT1, XMATRIX1, YMATRIX1, ZMATRIX1)
%  PARENT1:  hgtransform parent
%  XMATRIX1:  matrix of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data

%  Auto-generated by MATLAB on 25-Oct-2014 08:59:09

% Create hgtransform
hgtransform1 = hgtransform('Parent',Parent1);

% Create multiple lines using matrix input to plot3
plot3(XMatrix1,YMatrix1,ZMatrix1,'Parent',hgtransform1);

% Create text
text('Parent',hgtransform1,'String','X','Position',[1 0 0],'Color',[1 1 1]);

% Create text
text('Parent',hgtransform1,'String','Y','Position',[0 1 0],'Color',[1 1 1]);

% Create text
text('Parent',hgtransform1,'String','Z','Position',[0 0 1],'Color',[1 1 1]);

